apiVersion: apps/v1
kind: Deployment
metadata:
  name: ticketing-server-deployment
  namespace: ticketing
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ticketing-server
  template:
    metadata:
      labels:
        app: ticketing-server
    spec:
      containers:
      - name: ticketing-server
        image: public.ecr.aws/v3g6g4v7/ticketing-server:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        resources:
          requests:
            cpu: "250m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
