apiVersion: apps/v1
kind: Deployment
metadata:
  name: ticketing-server-deployment
  namespace: ticketing
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ticketing-server
  template:
    metadata:
      labels:
        app: ticketing-server
    spec:
      containers:
      - name: ticketing-server
        image: IMAGE_TAG
        imagePullPolicy: Always
        ports:
          - containerPort: 8000
        envFrom:
          - secretRef:
              name: ticketing-server-secret
        volumeMounts:
        - name: ticketing-server-secrets-volume
          mountPath: "/etc/secrets"
          readOnly: true
        resources:
          requests:
            cpu: "250m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
      volumes:
      - name: ticketing-server-secrets-volume
